/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClinicalReviewRouteImport } from './routes/clinical-review'
import { Route as DeviceRouteImport } from './routes/device'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as ModelLabRouteImport } from './routes/model-lab'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as ApiPublicDeviceRouteImport } from './routes/api/public/device'
import { Route as ApiPublicEncounterRouteImport } from './routes/api/public/encounter'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicalReviewRoute = ClinicalReviewRouteImport.update({
  id: '/clinical-review',
  path: '/clinical-review',
  getParentRoute: () => rootRouteImport,
} as any)
const DeviceRoute = DeviceRouteImport.update({
  id: '/device',
  path: '/device',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelLabRoute = ModelLabRouteImport.update({
  id: '/model-lab',
  path: '/model-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDeviceRoute = ApiPublicDeviceRouteImport.update({
  id: '/api/public/device',
  path: '/api/public/device',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicEncounterRoute = ApiPublicEncounterRouteImport.update({
  id: '/api/public/encounter',
  path: '/api/public/encounter',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clinical-review': typeof ClinicalReviewRoute
  '/device': typeof DeviceRoute
  '/mcp': typeof McpRoute
  '/model-lab': typeof ModelLabRoute
  '/reset-password': typeof ResetPasswordRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/api/public/device': typeof ApiPublicDeviceRoute
  '/api/public/encounter': typeof ApiPublicEncounterRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clinical-review': typeof ClinicalReviewRoute
  '/device': typeof DeviceRoute
  '/mcp': typeof McpRoute
  '/model-lab': typeof ModelLabRoute
  '/reset-password': typeof ResetPasswordRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/api/public/device': typeof ApiPublicDeviceRoute
  '/api/public/encounter': typeof ApiPublicEncounterRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clinical-review': typeof ClinicalReviewRoute
  '/device': typeof DeviceRoute
  '/mcp': typeof McpRoute
  '/model-lab': typeof ModelLabRoute
  '/reset-password': typeof ResetPasswordRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/api/public/device': typeof ApiPublicDeviceRoute
  '/api/public/encounter': typeof ApiPublicEncounterRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clinical-review'
    | '/device'
    | '/mcp'
    | '/model-lab'
    | '/reset-password'
    | '/.well-known/oauth-protected-resource'
    | '/.lovable/oauth/consent'
    | '/api/public/device'
    | '/api/public/encounter'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/clinical-review'
    | '/device'
    | '/mcp'
    | '/model-lab'
    | '/reset-password'
    | '/.well-known/oauth-protected-resource'
    | '/.lovable/oauth/consent'
    | '/api/public/device'
    | '/api/public/encounter'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
  id:
    | '__root__'
    | '/'
    | '/clinical-review'
    | '/device'
    | '/mcp'
    | '/model-lab'
    | '/reset-password'
    | '/.well-known/oauth-protected-resource'
    | '/.lovable/oauth/consent'
    | '/api/public/device'
    | '/api/public/encounter'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClinicalReviewRoute: typeof ClinicalReviewRoute
  DeviceRoute: typeof DeviceRoute
  McpRoute: typeof McpRoute
  ModelLabRoute: typeof ModelLabRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  ApiPublicDeviceRoute: typeof ApiPublicDeviceRoute
  ApiPublicEncounterRoute: typeof ApiPublicEncounterRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinical-review': {
      id: '/clinical-review'
      path: '/clinical-review'
      fullPath: '/clinical-review'
      preLoaderRoute: typeof ClinicalReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/device': {
      id: '/device'
      path: '/device'
      fullPath: '/device'
      preLoaderRoute: typeof DeviceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/model-lab': {
      id: '/model-lab'
      path: '/model-lab'
      fullPath: '/model-lab'
      preLoaderRoute: typeof ModelLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/device': {
      id: '/api/public/device'
      path: '/api/public/device'
      fullPath: '/api/public/device'
      preLoaderRoute: typeof ApiPublicDeviceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/encounter': {
      id: '/api/public/encounter'
      path: '/api/public/encounter'
      fullPath: '/api/public/encounter'
      preLoaderRoute: typeof ApiPublicEncounterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClinicalReviewRoute: ClinicalReviewRoute,
  DeviceRoute: DeviceRoute,
  McpRoute: McpRoute,
  ModelLabRoute: ModelLabRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  ApiPublicDeviceRoute: ApiPublicDeviceRoute,
  ApiPublicEncounterRoute: ApiPublicEncounterRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
