/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DeviceRouteImport } from './routes/device'
import { Route as ModelLabRouteImport } from './routes/model-lab'
import { Route as ApiPublicDeviceRouteImport } from './routes/api/public/device'
import { Route as ApiPublicEncounterRouteImport } from './routes/api/public/encounter'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeviceRoute = DeviceRouteImport.update({
  id: '/device',
  path: '/device',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelLabRoute = ModelLabRouteImport.update({
  id: '/model-lab',
  path: '/model-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDeviceRoute = ApiPublicDeviceRouteImport.update({
  id: '/api/public/device',
  path: '/api/public/device',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicEncounterRoute = ApiPublicEncounterRouteImport.update({
  id: '/api/public/encounter',
  path: '/api/public/encounter',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/device': typeof DeviceRoute
  '/model-lab': typeof ModelLabRoute
  '/api/public/device': typeof ApiPublicDeviceRoute
  '/api/public/encounter': typeof ApiPublicEncounterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/device': typeof DeviceRoute
  '/model-lab': typeof ModelLabRoute
  '/api/public/device': typeof ApiPublicDeviceRoute
  '/api/public/encounter': typeof ApiPublicEncounterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/device': typeof DeviceRoute
  '/model-lab': typeof ModelLabRoute
  '/api/public/device': typeof ApiPublicDeviceRoute
  '/api/public/encounter': typeof ApiPublicEncounterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/device'
    | '/model-lab'
    | '/api/public/device'
    | '/api/public/encounter'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/device'
    | '/model-lab'
    | '/api/public/device'
    | '/api/public/encounter'
  id:
    | '__root__'
    | '/'
    | '/device'
    | '/model-lab'
    | '/api/public/device'
    | '/api/public/encounter'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DeviceRoute: typeof DeviceRoute
  ModelLabRoute: typeof ModelLabRoute
  ApiPublicDeviceRoute: typeof ApiPublicDeviceRoute
  ApiPublicEncounterRoute: typeof ApiPublicEncounterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/device': {
      id: '/device'
      path: '/device'
      fullPath: '/device'
      preLoaderRoute: typeof DeviceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/model-lab': {
      id: '/model-lab'
      path: '/model-lab'
      fullPath: '/model-lab'
      preLoaderRoute: typeof ModelLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/device': {
      id: '/api/public/device'
      path: '/api/public/device'
      fullPath: '/api/public/device'
      preLoaderRoute: typeof ApiPublicDeviceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/encounter': {
      id: '/api/public/encounter'
      path: '/api/public/encounter'
      fullPath: '/api/public/encounter'
      preLoaderRoute: typeof ApiPublicEncounterRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DeviceRoute: DeviceRoute,
  ModelLabRoute: ModelLabRoute,
  ApiPublicDeviceRoute: ApiPublicDeviceRoute,
  ApiPublicEncounterRoute: ApiPublicEncounterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
