/* Prototype hospital fleet. Local demo data only — never persisted. */

export const CARTS = [
  {
    id: "sah-c1",
    facility: "saint",
    name: "Tele-Cart 1",
    unit: "MICU",
    room: "412",
    state: "requested",
    nurse: "N. Alvarez, RN",
    patient: "R. Whitfield",
    acuity: "critical",
    waitedMin: 4,
    mintti: "assigned",
    minttiBattery: 82,
  },
  {
    id: "sah-c2",
    facility: "saint",
    name: "Tele-Cart 2",
    unit: "ED Bay",
    room: "7",
    state: "available",
    nurse: "K. Osei, RN",
    patient: null,
    acuity: null,
    waitedMin: 0,
    mintti: "assigned",
    minttiBattery: 61,
  },
  {
    id: "sah-w1",
    facility: "saint",
    name: "Wall Station · 5 West",
    unit: "5 West",
    room: "512",
    state: "preparing",
    nurse: "D. Park, RN",
    patient: "M. Ibarra",
    acuity: "urgent",
    waitedMin: 11,
    mintti: "none",
    minttiBattery: null,
  },
  {
    id: "edg-c1",
    facility: "edgerton",
    name: "Tele-Cart A",
    unit: "Step-down",
    room: "218",
    state: "requested",
    nurse: "J. Boone, RN",
    patient: "L. Chen",
    acuity: "urgent",
    waitedMin: 19,
    mintti: "ready",
    minttiBattery: 45,
  },
  {
    id: "edg-c2",
    facility: "edgerton",
    name: "Tele-Cart B",
    unit: "Med-Surg",
    room: "233",
    state: "setup",
    nurse: "Unassigned",
    patient: null,
    acuity: null,
    waitedMin: 0,
    mintti: "none",
    minttiBattery: null,
  },
  {
    id: "mcw-c1",
    facility: "mercy",
    name: "Tele-Cart 3",
    unit: "ICU",
    room: "104",
    state: "available",
    nurse: "S. Rowe, RN",
    patient: null,
    acuity: null,
    waitedMin: 0,
    mintti: "ready",
    minttiBattery: 93,
  },
  {
    id: "mcw-c2",
    facility: "mercy",
    name: "Tele-Cart 4",
    unit: "PACU",
    room: "3",
    state: "offline",
    nurse: "Unassigned",
    patient: null,
    acuity: null,
    waitedMin: 0,
    mintti: "none",
    minttiBattery: null,
  },
  {
    id: "nlc-c1",
    facility: "northline",
    name: "Peds Cart 1",
    unit: "PICU",
    room: "8",
    state: "requested",
    nurse: "A. Farrow, RN",
    patient: "T. Okafor",
    acuity: "routine",
    waitedMin: 34,
    mintti: "assigned",
    minttiBattery: 70,
  },
];

export const MINTTI_FIELD = {
  ready: { label: "Marked ready", tone: "#12B76A" },
  assigned: { label: "Assigned", tone: "#2E5CFF" },
  none: { label: "Not assigned", tone: "#98A2B3" },
};
